name: 5 - Env
on: [push]
env:
  WORKFLOW_ENV: 'workflow env'
jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: 'job env'
    steps:
      - run: echo ${{ env.WORKFLOW_ENV }}
      - run: echo ${{ env.JOB_ENV }}