name: 09 - Setup Environment
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y cowsay
      - run: cowsay "Hello World"