name: Manual Trigger
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'What do you want to say?'
        required: true
        default: 'Hi!'
        type: string
  push:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.inputs.message }}, you said."